# export extensions with: code --list-extensions | xargs -L 1 echo code --install-extension

code --install-extension aeschli.vscode-css-formatter
code --install-extension alexkrechik.cucumberautocomplete
code --install-extension Arjun.swagger-viewer
code --install-extension bibhasdn.django-html
code --install-extension bibhasdn.django-snippets
code --install-extension blzjns.vscode-raml
code --install-extension chriswheeldon.exuberant-ctags
code --install-extension codecov.codecov
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension eamodio.gitlens
code --install-extension ecmel.vscode-html-css
code --install-extension esbenp.prettier-vscode
code --install-extension ginfuru.ginfuru-vscode-jekyll-syntax
code --install-extension github.vscode-github-actions
code --install-extension GitHub.vscode-pull-request-github
code --install-extension golang.go
code --install-extension GrapeCity.gc-excelviewer
code --install-extension hashicorp.terraform
code --install-extension jetmartin.bats
code --install-extension jinliming2.vscode-go-template
code --install-extension lextudio.restructuredtext
code --install-extension mechatroner.rainbow-csv
code --install-extension mikestead.dotenv
code --install-extension mohd-akram.vscode-html-format
code --install-extension ms-azuretools.vscode-docker
code --install-extension MS-CEINTL.vscode-language-pack-pt-BR
code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
code --install-extension ms-mssql.data-workspace-vscode
code --install-extension ms-mssql.mssql
code --install-extension ms-mssql.sql-database-projects-vscode
code --install-extension ms-python.black-formatter
code --install-extension ms-python.isort
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --install-extension ms-toolsai.vscode-jupyter-slideshow
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode.makefile-tools
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension njpwerner.autodocstring
code --install-extension redhat.vscode-yaml
code --install-extension scanapi.scanapi
code --install-extension Shopify.ruby-lsp
code --install-extension Shopify.theme-check-vscode
code --install-extension sissel.shopify-liquid
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension syler.sass-indented
code --install-extension tamasfe.even-better-toml
code --install-extension tombonnike.vscode-status-bar-format-toggle
code --install-extension Tyriar.sort-lines
code --install-extension uctakeoff.vscode-counter
code --install-extension uloco.theme-bluloco-dark
code --install-extension uloco.theme-bluloco-light
code --install-extension vscode-icons-team.vscode-icons
code --install-extension WakaTime.vscode-wakatime
code --install-extension wholroyd.jinja
code --install-extension ZainChen.json
code --install-extension ziyasal.vscode-open-in-github
