code --install-extension AlanWalk.markdown-toc
code --install-extension alexkrechik.cucumberautocomplete
code --install-extension bibhasdn.django-html
code --install-extension bibhasdn.django-snippets
code --install-extension blzjns.vscode-raml
code --install-extension bungcip.better-toml
code --install-extension chriswheeldon.exuberant-ctags
code --install-extension GitHub.vscode-pull-request-github
code --install-extension GrapeCity.gc-excelviewer
code --install-extension kiteco.kite
code --install-extension lextudio.restructuredtext
code --install-extension mauve.terraform
code --install-extension mechatroner.rainbow-csv
code --install-extension mikestead.dotenv
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
code --install-extension ms-mssql.mssql
code --install-extension ms-python.python
code --install-extension ms-vscode.Go
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension njpwerner.autodocstring
code --install-extension redhat.vscode-yaml
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension Tyriar.sort-lines
code --install-extension uloco.theme-bluloco-dark
code --install-extension uloco.theme-bluloco-light
code --install-extension vscode-icons-team.vscode-icons
code --install-extension WakaTime.vscode-wakatime
code --install-extension wholroyd.jinja
code --install-extension ziyasal.vscode-open-in-github
